import React from 'react';
import QRCode from 'react-qr-code';
import styles from './ShareableCard.module.css';

interface ShareableCardProps {
  data: {
    name: string;
    avatar: string;
    startAge: number;
    salary: number;
    monthlySavings: number;
    retireAge: number;
    monthlyExpense: number;
    lifeExpectancy: number;
  };
  theme: string;
}

const ShareableCard: React.FC<ShareableCardProps> = ({ data, theme }) => {
  const getFinancialPersona = (totalSavings: number) => {
    if (totalSavings > 1000000) return 'Future Mogul';
    if (totalSavings > 500000) return 'Side-Hustle Superstar';
    return 'Chillonaire';
  };

  const workingYears = data.retireAge - data.startAge;
  const totalSavings = data.monthlySavings * workingYears * 12;
  const yearsToChillax = data.lifeExpectancy - data.retireAge;
  const financialPersona = getFinancialPersona(totalSavings);
  const appUrl = typeof window !== 'undefined' ? window.location.origin : '';

  return (
    <div id="shareable-card" className={`${styles.cardContainer} ${theme}`}>
      <div className={styles.cardHeader}>
        <img src={data.avatar} alt={data.name} className={styles.avatar} />
        <h2 className={styles.personaTitle}>{financialPersona}</h2>
      </div>
      <div className={styles.cardBody}>
        <h3 className={styles.name}>{data.name}</h3>
        <div className={styles.statsGrid}>
          <div className={styles.statItem}>
            <span className={styles.statLabel}>Total Stash</span>
            <span className={styles.statValue}>${(totalSavings / 1000).toFixed(0)}k</span>
          </div>
          <div className={styles.statItem}>
            <span className={styles.statLabel}>Years to Chillax</span>
            <span className={styles.statValue}>{yearsToChillax}</span>
          </div>
        </div>
        <div className={styles.qrCodeContainer}>
          <QRCode value={appUrl} size={64} bgColor="transparent" fgColor="currentColor" />
        </div>
      </div>
      <div className={styles.cardFooter}>
        <p>Generated by YourApp</p>
      </div>
    </div>
  );
};

export default ShareableCard;
